In [77]:
from array import*
vals = array('i',[5,8,9,6])
print(vals)

array('i', [5, 8, 9, 6])


In [2]:
from array import*
vals = array('i',[5,8,9,6])
print(vals.typecode)

i


In [9]:
from array import*
vals = array('i',[5,8,9,6])
vals.reverse()
print(vals)

array('i', [6, 9, 8, 5])


In [10]:
from array import*
vals = array('i',[5,8,9,6])
print(vals[0])

5


In [11]:
from array import*
vals = array('i',[5,8,9,6])
for i in range(5):
    print(vals[i])

5
8
9
6


IndexError: array index out of range

In [13]:
from array import*
vals = array('i',[5,8,9,6])
for i in range(0,len(vals)):
    print(vals[i])

5
8
9
6


In [15]:
from array import*
vals = array('i',[5,8,9,6])
for i in vals:
    print(i)

5
8
9
6


In [17]:
from array import*
vals = array('u',['a','e','i'])
for i in vals:
    print(i)

a
e
i


In [24]:
from array import*
vals = array('i',[5,8,9,6])
newarr = array(vals.typecode,(a for a in vals))
for i in newarr:
    print(i)

5
8
9
6


In [25]:
from array import*
vals = array('i',[5,8,9,6])
newarr = array(vals.typecode,(a*a for a in vals))
for i in newarr:
    print(i)

25
64
81
36


In [27]:
from array import*
vals = array('i',[5,8,9,6])
newarr = array(vals.typecode,(a*a for a in vals))
i = 0
while(i<len(newarr)):
    print(newarr[i])
    i+=1

25
64
81
36


In [ ]:
examples.........

In [29]:
from array import*

arr=array('i',[])
n = int(input("enter the length of array:"))

for i in range(n):
    x = int(input("enter next value:"))
    arr.append(x)
    
print(arr)

val = int(input("enter the value for search:"))

k = 0
for e in arr:
    if(e==val):
        print(k)
    k+=1

enter the length of array:3
enter next value:4
enter next value:5
enter next value:1
array('i', [4, 5, 1])
enter the value for search:4
0


In [69]:
arr=array('i',[])
n = int(input("enter the length of array:"))

for i in range(n):
    x = int(input("enter next value:"))
    arr.append(x)
    
print(arr)

val = int(input("enter the value for search:"))

print(arr.index(val))

enter the length of array:3
enter next value:1
enter next value:2
enter next value:3
array('i', [1, 2, 3])
enter the value for search:2
1


In [54]:
import array as arr
a = arr.array('i', [1, 2, 3]) 

for i in range(3):
    print(a[i],end = " ")
print()

a.insert(2,4)
for i in a:
    print(i, end = " ")
print()

b = arr.array('d',[2.5,3.8,4.6])
for i in b:
    print(i,end = " ")
print()

b.append(4.4)
for i in b:
    print(i,end= " ")
print()
print("popped element is:", end=" ")

print(b.pop(1))
for i in b:
    print(i,end = " ")
print()

b.remove(2.5)
for i in b:
    print(i,end = " ")
print()
    

    

1 2 3 
1 2 4 3 
2.5 3.8 4.6 
2.5 3.8 4.6 4.4 
popped element is: 3.8
2.5 4.6 4.4 
4.6 4.4 


In [109]:
a = [1,2,3,4,5,6,7,8,9]
arr = array('i',a)
print("intial array:", end = " ")
for i in a:
    print(i, end = " ")

sliced = a[3:8] 
print("\nsliced array:")
print(sliced)

intial array: 1 2 3 4 5 6 7 8 9 
sliced array:
[4, 5, 6, 7, 8]


In [68]:
a = [1,2,3,4,5,6,7,8,9]
arr = array('i',a)
print("intial array:", end = " ")
for i in a:
    print(i, end = " ")


print("\nsliced array:")
print(a[3:8])

intial array: 1 2 3 4 5 6 7 8 9 
sliced array:
[4, 5, 6, 7, 8]


In [75]:
a = array('i',[1,2,3,1,4,5])
for i in a:
    print(i,end = " ")
print("\r")
    
a[2] = 6
for i in range(0,len(a)):
        print(a[i],end = " ")

1 2 3 1 4 5 
1 2 6 1 4 5 

In [8]:
from array import*
x = array('u',['a','b','c'])
for i in range(3):
    print(x[i])

a
b
c


In [12]:
import numpy as np
heights = [1.25,2.25,4.52,3.25]
x = np.array(heights)
print(x)

weights = [65.4,85.4,45.2,75.5]
y=np.array(weights)
print(y)

bmi = x/y**2
print(bmi)

[1.25 2.25 4.52 3.25]
[65.4 85.4 45.2 75.5]
[0.00029225 0.00030851 0.00221239 0.00057015]


0.0003085082460826308

In [32]:
np.corrcoef(x[:,0],x[:,1])

array([[1., 1.],
       [1., 1.]])

In [36]:
np.std(x[:,0])

1.5

In [9]:
bmi<1

array([ True,  True,  True,  True])

In [13]:
bmi[bmi>0.00030]

array([0.00030851, 0.00221239, 0.00057015])

In [14]:
type(x)

numpy.ndarray

In [ ]:
ndarray = N-dimensional array

In [22]:
x = np.array([[1,2,3,5,8],[4,9,7,5,6]])
x

array([[1, 2, 3, 5, 8],
       [4, 9, 7, 5, 6]])

In [23]:
x[:,1:3]

array([[2, 3],
       [9, 7]])

In [39]:
np.std(x[1,:])

1.7204650534085255

In [41]:
heights= [5.2,5.4,6.0,5.9,5.8,5.6,5.3,5.7,5.4,5.2]
x = np.array(heights)
x
weights = [65,58,72,80,75,76,74,73,71,72]
y = np.array(weights)
y

array([65, 58, 72, 80, 75, 76, 74, 73, 71, 72])

In [50]:
city = np.column_stack((heights,weights))
city

array([[ 5.2, 65. ],
       [ 5.4, 58. ],
       [ 6. , 72. ],
       [ 5.9, 80. ],
       [ 5.8, 75. ],
       [ 5.6, 76. ],
       [ 5.3, 74. ],
       [ 5.7, 73. ],
       [ 5.4, 71. ],
       [ 5.2, 72. ]])

In [52]:
city = np.row_stack((heights,weights))
city

array([[ 5.2,  5.4,  6. ,  5.9,  5.8,  5.6,  5.3,  5.7,  5.4,  5.2],
       [65. , 58. , 72. , 80. , 75. , 76. , 74. , 73. , 71. , 72. ]])

In [42]:
x.mean()

5.55

In [43]:
x.std()

0.27658633371878655

In [44]:
y.mean()

71.6

In [45]:
y.std()

5.817215828899595

In [47]:
height = np.round(np.random.normal(5.55,0.2766,10),2)
weight = np.round(np.random.normal(71.6,5.8172,10),2)
city = np.column_stack((heights,weights))
city

array([[ 5.2, 65. ],
       [ 5.4, 58. ],
       [ 6. , 72. ],
       [ 5.9, 80. ],
       [ 5.8, 75. ],
       [ 5.6, 76. ],
       [ 5.3, 74. ],
       [ 5.7, 73. ],
       [ 5.4, 71. ],
       [ 5.2, 72. ]])

In [25]:
x[1,:]

array([4, 9, 7, 5, 6])

In [27]:
x.mean()

5.0

In [28]:
np.mean(x[:,0])

2.5

In [29]:
np.mean(x[0,:])

3.8

In [30]:
np.median(x[0,:])

3.0

In [16]:
x.shape

(2, 3)

In [20]:
x[0][2]

3

In [21]:
x[0,2]

3

In [ ]:
x[:,]

In [4]:
import md as k


In [5]:
k.f1(15,20)

('lcm=', 60)

In [6]:
import hcfpn as b
b.p1(25)

'it is not prime  number'

In [7]:
b.h2(45,70)

5 is HCF
