In [3]:
a= [3,4,6,9,8]
b=[3,4,12,6,8,9,12,11,20]
c= a+b
def f1(x):
    k = 0
    for i in x:
        k = k+i
    print (k)
f1(a)
f1(b)
f1(c)

30
85
115


In [7]:
def f2():
    x= 2
    y=5
    return(x+y)
f2()
    

7

In [10]:
def f3(x,y):
    return(x+y)
f3(3,4)

7

In [11]:
def f3(x,y):
    if (x<y):
        z = y-x
    else:
        z=x-y
    print (z)
f3(3,4)

1


In [5]:
def f6(x,*y):
    y = list(y)
    k =0
    for i in y:
        k=k+i
    k=k+x
    print (k)
f6(3,5,2,5,6)

21


In [15]:
def f7(*y):
    y = list(y)
    a = y[0]
    for i in y:
        if (i> a ):
            a = i
    print (a)
    k=1
    for i in y:
        k = k*i
    print (k)
    for i in range(a,k+1):
        count = 0
        for j in y:
            if (i%j==0):
                count+=1
        if (count == len(y)):
            print ("lcm:",i)
            break
        
    
f7(12,36,6,84,92)
    

92
20030976
lcm: 5796


In [18]:
def f7(*y):
    y = list(y)
    a = y[0]
    
    for i in y:
        if (i> a ):
            a = i
    print (a)
    k=1
    for i in y:
        k = k*i
    print (k)
    for i in range(a,k+1):
        count = 0
        for j in y:
            if (i%j==0):
                count+=1
        if (count == len(y)):
            print ("lcm:",i)
            break
        
    
f7(12,36,6,84,92)
    
    

92
20030976
lcm: 5796


In [25]:
def f8(x):
    k =0
    i =0
    for i in range(1,x+1):
        if (x%i==0):
            k= k +1
        i= i+ 1
    if (k==2):
        print ("prime")
    else:
        print("not")
    
f8(2)   

prime


In [30]:
def f9(x,*y):
    y= list(y)
    y.append(x)
    print(y)
    p=0
    q=len(y)
    while(p<q):
        a = y[p]
        k =0
        i =1
        for i in range(1,a+1):
            if (a%i==0):
                k= k +1
            i= i+ 1
        p=p+1
        if (k==2):
            print ("prime")
        else:
            print("not")
    
f9(13,15,48,58,2)

[15, 48, 58, 2, 13]
not
not
not
prime
prime


In [11]:
def f10(x,*y):
    y = list(y)
    y.insert(0,x)
    print(y)
    for i in y:
        if (i%2==0):
            print(i)
            
    
    
f10(3,6,8,5,7,9)

[3, 6, 8, 5, 7, 9]
6
8


In [20]:
def add(x,y):
    return(x+y)
def subtract(x,y):
    return(x-y)

print("please select operation-\n 1. add\n 2.subtract\n")
      
select = input("select operations from 1,2:")
num1= int(input("enter first number: "))
num2= int(input("enter second number: "))

if (select=='1'):
    print(num1,"+",num2,"=",add(num1,num2))
elif(select=='2'):
    print(num1,"-",num2,"=", subtract(num1,num2))
else:
    print("invalid")




please select operation-
 1. add
 2.subtract

select operations from 1,2:2
enter first number: 5
enter second number: 2
5 - 2 = 3


In [ ]:
sum of values at even places and odd values.....

In [17]:
def f11(x,*y):
    y=list(y)
    y.append(x)
    print(y)
    p=[]
    q=[]
    a = len(y)
    for i in range(0,a):
        if(i%2==0):
            p.append(y[i])
    print(p)
    for i in y:
        if(i%2!=0):
            q.append(i)
    print(q)
    k = []
    for i in range(0,len(p)):
        k.append(p[i] + q[i])
    print(k)
f11(12,44,84,16,13,24,47,79,75,99)

[44, 84, 16, 13, 24, 47, 79, 75, 99, 12]
[44, 16, 24, 79, 99]
[13, 47, 79, 75, 99]
[57, 63, 103, 154, 198]


In [3]:
def add(x,y):
    z = x+y
    print(z)
def sub(x,y):
    z = x-y
    print(z)
def d(x):
    if(x>4):
        add(5,3)
    else:
        sub(5,3)
d(7)

8


In [3]:

def a(k):
    
    print("india")
    k=k+1
    print(k)
    a(k)
    
    
a(1)


india
2
india
3
india
4
india
5
india
6
india
7
india
8
india
9
india
10
india
11
india
12
india
13
india
14
india
15
india
16
india
17
india
18
india
19
india
20
india
21
india
22
india
23
india
24
india
25
india
26
india
27
india
28
india
29
india
30
india
31
india
32
india
33
india
34
india
35
india
36
india
37
india
38
india
39
india
40
india
41
india
42
india
43
india
44
india
45
india
46
india
47
india
48
india
49
india
50
india
51
india
52
india
53
india
54
india
55
india
56
india
57
india
58
india
59
india
60
india
61
india
62
india
63
india
64
india
65
india
66
india
67
india
68
india
69
india
70
india
71
india
72
india
73
india
74
india
75
india
76
india
77
india
78
india
79
india
80
india
81
india
82
india
83
india
84
india
85
india
86
india
87
india
88
india
89
india
90
india
91
india
92
india
93
india
94
india
95
india
96
india
97
india
98
india
99
india
100
india
101
india
102
india
103
india
104
india
105
india
106
india
107
india
108
india
109
india
110
india
111
india


india
1484
india
1485
india
1486
india
1487
india
1488
india
1489
india
1490
india
1491
india
1492
india
1493
india
1494
india
1495
india
1496
india
1497
india
1498
india
1499
india
1500
india
1501
india
1502
india
1503
india
1504
india
1505
india
1506
india
1507
india
1508
india
1509
india
1510
india
1511
india
1512
india
1513
india
1514
india
1515
india
1516
india
1517
india
1518
india
1519
india
1520
india
1521
india
1522
india
1523
india
1524
india
1525
india
1526
india
1527
india
1528
india
1529
india
1530
india
1531
india
1532
india
1533
india
1534
india
1535
india
1536
india
1537
india
1538
india
1539
india
1540
india
1541
india
1542
india
1543
india
1544
india
1545
india
1546
india
1547
india
1548
india
1549
india
1550
india
1551
india
1552
india
1553
india
1554
india
1555
india
1556
india
1557
india
1558
india
1559
india
1560
india
1561
india
1562
india
1563
india
1564
india
1565
india
1566
india
1567
india
1568
india
1569
india
1570
india
1571
india
1572
india
1573
india
1574

india
2926
india
2927
india
2928
india
2929
india
2930
india
2931
india
2932
india
2933
india
2934
india
2935
india
2936
india
2937
india
2938
india
2939
india
2940
india
2941
india
2942
india
2943
india
2944
india
2945
india
2946
india
2947
india
2948
india
2949
india
2950
india
2951
india
2952
india
2953
india
2954
india
2955


RecursionError: maximum recursion depth exceeded while calling a Python object

In [3]:
print(k)

0


In [9]:
print("factorial of 6")
def fact(x):
    if(x==0):
        return(1)
    else:
        return(x*fact(x-1))
    print(x)
fact(6)

factorial of 6


720

In [8]:
print("5+4+3+2+1+1")
def sum(x):
    if (x==0):
        return (1)
    else:
        return(x+sum(x-1))
    print(x)
    
sum(5)

5+4+3+2+1+1


16

In [10]:
x =4
def f1(y):
    x = y+3
    print(x)
print(x)
f1(4)

4
7


In [12]:
x =4
def f1(y):
    global x
    x = y+3
    print(x)
print(x)
f1(4)
print(x)

4
7
7


In [13]:
x

7

In [2]:
l = [3,4,2,8]
y=2*l
print(y)
x1 = [8,9,7,2]
y= l+x1
print(y)

[3, 4, 2, 8, 3, 4, 2, 8]
[3, 4, 2, 8, 8, 9, 7, 2]


In [18]:
y = lambda a,b:a-b
print(y)
y(3,4)

<function <lambda> at 0x0000019D786AC158>


-1

In [22]:
a =[3,4,7,12,9,16]
p = list(filter(lambda k:k%2==0,a))
print(p)

[4, 12, 16]


In [3]:
a =[3,4,7,12,9,16]
p=list(filter(lambda k:k%2!=0,a))
print(9)

[3, 7, 9]

In [25]:
a =[3,4,7,12,9,16]
p = list(filter(lambda k:k%2,a))
print(p)

[3, 7, 9]


In [31]:
a = [3,4,7,12,9,16]
def f1(x):
    return(x%2==0)
list(filter(f1,a))


[4, 12, 16]

In [32]:
a = [3,4,7,12,9,16]
def f2(x):
    return(x%2==0)
list(map(f2,a))


[False, True, False, True, False, True]

In [37]:
n = 10
r = 4
p =n-r
def fact(x):
    if(x==0):
        return(1)
    else:
        return(x*fact(x-1))
P = fact(n)
Q = fact(r)
R = fact(p)
c= P/(Q*R)
print(c)

210.0


In [7]:
import numpy as np
x = np.array([3,4,6])
y = np.array([7,6,8])
z= x*2
print(z)

[ 6  8 12]


In [47]:
import numpy as np
l = [3,4,8]
y= np.array(l)
print(y)

[3 4 8]


In [8]:

k = [3,5,8,9]
y = np.array(k)
z = y**2
print(z)

[ 9 25 64 81]


In [55]:
x = [4,6,8,10]
y = [2,3,4,5]
a = np.array(x)
b = np.array(y)
p = a**2 - b**2
k = 0
for i in p:
    k=k+i
print(k)

162


In [56]:
x = [4,6,8,10]
y = [2,3,4,5]
a = np.array(x)
b = np.array(y)
p = a**2 - b**2
q = np.sum(p)
print(q)

162


In [3]:
import numpy as np
l = [3,4,6,8]
y = np.array(l)

print(y)

[3 4 6 8]


In [4]:
y.mean()

5.25

In [5]:
y.min()

3

In [6]:
y.max()

8

In [10]:
y=np.array([[3,4],[1,8]])
print(y)

[[3 4]
 [1 8]]


In [11]:
y[0,0]

3

In [13]:
y[0,1]

4

In [14]:
y[1,0]

1

In [15]:
y[1,1]

8

In [17]:
y= np.mat('1,2;4,5')
y

matrix([[1, 2],
        [4, 5]])

In [10]:
y= np.mat('1,2,3;4,5,8;5,7,6')
print(y)

[[1 2 3]
 [4 5 8]
 [5 7 6]]


In [9]:
z = np.mat('5,4,9;3,2,4;1,7,6')
print(z)

[[5 4 9]
 [3 2 4]
 [1 7 6]]


In [12]:
print(y+z)

[[ 6  6 12]
 [ 7  7 12]
 [ 6 14 12]]


In [46]:
y = np.mat('1,2,3;4,5,6;7,8,9')
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
y[0,1]

2

In [8]:
import numpy as np
y = np.mat('1,2,3;4,5,6;7,8,9')
k = 0
for i in range(0,3):
    k = k+y[i,0] + y [i,2]
print(k)

30


In [28]:
k = 0
for i in range(0,3):
    k = k+y[0,i]
print(k)

6


In [29]:
k = 0
for i in range(0,3):
    k = k+y[i,2]
print(k)

18


In [36]:
p =0
k=0
for i in range(0,2):
    for j in range(0,3):
        k = k +y[j,p]
    p=p+2
print(k)

30


In [40]:
k = 0

for i in range(0,3):
    for j in range(0,3):
        if (i==j):
            k = k +y[j,i]
   
print(k)

15


In [41]:
k = 0
for i in range(0,3):
    k = k+ y[i,i]
print(k)

15


In [47]:
for i in range(0,3):
    y[i,0]=6
print(y)
            
            

[[6 2 3]
 [6 5 6]
 [6 8 9]]


In [50]:
y = np.array([1,2,3,4,5,6,7,8,9])
print(y)

[1 2 3 4 5 6 7 8 9]


In [51]:
z = np.mat(y.reshape(3,3))
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
y = np.mat('1,2,3;4,5,6;7,8,9')
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
k=y.getI()
print(k)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [56]:
z = y.getT()
print(z)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [58]:
A =y.T
print(A)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [60]:
X = y.shape
print(X)

(3, 3)


In [61]:
y.size

9

In [10]:
y = np.array([1,2,3])
x = np.mat('4,2,8;,9,6,3;7,1,5')
z = y+x
print(z)

[[ 5  4 11]
 [10  8  6]
 [ 8  3  8]]


In [11]:
y = np.array([1,2,3])
x = np.mat('4,2,8;,9,6,3;7,1,5')
z = y+x
print(z)

[[ 5  4 11]
 [10  8  6]
 [ 8  3  8]]


In [71]:
p = np.mat('1,2,3;4,5,6;7,8,9')
q = np.mat('9,8,7;6,5,4;3,2,1')
print(p)
print(q)
z = p.dot(q)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [14]:
p = np.mat('1,2,3;4,5,6;7,8,9')
q = np.mat('9,8,7;6,5,4;3,2,1')
print(p)
print(q)
z = p*q
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [90]:
p=x.dot(y)
p

28

In [91]:
x1=x**2
x1
y1=y**2
y1

array([ 4, 16, 36], dtype=int32)

In [92]:
x2=x1.sum()
x2
y2=y1.sum()
y2

56

In [93]:
x3=np.sqrt(x2)
x3
y3=np.sqrt(y2)
y3

7.483314773547883

In [95]:
k=x3*y3

In [96]:
p/k

1.0

In [3]:
def f7(x,*y):
    y = list(y)
    y.append(x)
    a = y[0]
    for i in y:
        if (i<a):
            a = i
    print("min:",a)
    while (a>0):
        count = 0
        for i in y:
            if (i%a==0):
                count = count +1
        if (count==len(y)):
            print("hcf:",a)
            break
        a=a-1
f7(12,36,6,84,92)

min: 6
hcf: 2
