In [24]:
import random                             #y = mx+c and m =4, c= 5
x = []    
y = []
for i in range(0,50):
    x.append(i)
    p = random.random()                   #p = error values
    y.append(4*i+ 5 + p)
print(x)
print(y)

x1 = []                  #break x into 70:30 ratio i.e. 35 and 15
y1 = []
x2 = []
y2 = []
for i in range(0,35):
    x1.append(x[i])
    y1.append(y[i])
for i in range(0,15):
    x2.append(x[i+35])
    y2.append(y[i+35])
    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[5.998046316567253, 9.248623712090286, 13.782954053399289, 17.40423013293531, 21.121574349278497, 25.63825656907024, 29.37183296567659, 33.17628385145676, 37.27549262460583, 41.87528987059421, 45.13753026883791, 49.84285737266578, 53.57274705445009, 57.47735196954466, 61.270944038291546, 65.6021682143029, 69.43543113779579, 73.64645722500498, 77.18820689574436, 81.19481044956892, 85.15673190817884, 89.04078677775995, 93.37612417946696, 97.33140167563295, 101.10564160616873, 105.78780208838889, 109.27442723397209, 113.34916788066151, 117.42274459165301, 121.46335654675465, 125.06531314802622, 129.73425781456882, 133.12136526148723, 137.76320757401467, 141.82670011494585, 145.78124319416267, 149.764498525488, 153.03086623201082, 157.42743202356542, 161.84611430438596, 165.41294258100842, 169.67172213

In [25]:
print(x1)
print(y1)
print(x2)
print(y2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]
[5.998046316567253, 9.248623712090286, 13.782954053399289, 17.40423013293531, 21.121574349278497, 25.63825656907024, 29.37183296567659, 33.17628385145676, 37.27549262460583, 41.87528987059421, 45.13753026883791, 49.84285737266578, 53.57274705445009, 57.47735196954466, 61.270944038291546, 65.6021682143029, 69.43543113779579, 73.64645722500498, 77.18820689574436, 81.19481044956892, 85.15673190817884, 89.04078677775995, 93.37612417946696, 97.33140167563295, 101.10564160616873, 105.78780208838889, 109.27442723397209, 113.34916788066151, 117.42274459165301, 121.46335654675465, 125.06531314802622, 129.73425781456882, 133.12136526148723, 137.76320757401467, 141.82670011494585]
[35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[145.78124319416267, 149.764498525488, 153.03086623201082, 157.42743202356542, 161.84611430438596, 165.41294258100842, 169.671722

In [26]:
import numpy as np
x1 = np.array(x1)
x2 = np.array(x2)
y1 = np.array(y1)
y2 = np.array(y2)
w0 = random.random()
w1 = random.random()
yp1 = w0 + w1 * x1            #choose model or hypohesis                                                                                                                                                                
yp1

array([0.83670641, 0.88303965, 0.92937288, 0.97570611, 1.02203934,
       1.06837258, 1.11470581, 1.16103904, 1.20737227, 1.2537055 ,
       1.30003874, 1.34637197, 1.3927052 , 1.43903843, 1.48537166,
       1.5317049 , 1.57803813, 1.62437136, 1.67070459, 1.71703783,
       1.76337106, 1.80970429, 1.85603752, 1.90237075, 1.94870399,
       1.99503722, 2.04137045, 2.08770368, 2.13403691, 2.18037015,
       2.22670338, 2.27303661, 2.31936984, 2.36570308, 2.41203631])

In [27]:
y1

array([  5.99804632,   9.24862371,  13.78295405,  17.40423013,
        21.12157435,  25.63825657,  29.37183297,  33.17628385,
        37.27549262,  41.87528987,  45.13753027,  49.84285737,
        53.57274705,  57.47735197,  61.27094404,  65.60216821,
        69.43543114,  73.64645723,  77.1882069 ,  81.19481045,
        85.15673191,  89.04078678,  93.37612418,  97.33140168,
       101.10564161, 105.78780209, 109.27442723, 113.34916788,
       117.42274459, 121.46335655, 125.06531315, 129.73425781,
       133.12136526, 137.76320757, 141.82670011])

In [28]:
error = (sum((y1-yp1)**2))/70

In [29]:
error                        #method use to reduce error is gradian decent

3374.348914988062

In [30]:
dj0 = (sum(y1 - yp1))/35           #dj0 = dj/dw0 and dj1 = dj/dw1
dj1 = (sum((y1 - yp1) * x1))/35

In [31]:
dj0

71.80648913804652

In [32]:
dj1

1623.7369053098728

In [33]:
alpha = 0.001

In [34]:
w0 = w0 + (alpha*dj0)
w1 = w1 + (alpha*dj1)

In [35]:
w0

0.9085129040736822

In [36]:
w1

1.6700701374429596

In [37]:
yp1 = w0 + w1 * x1                                             #choose linear                                                                                                                                                                     
yp1

array([ 0.9085129 ,  2.57858304,  4.24865318,  5.91872332,  7.58879345,
        9.25886359, 10.92893373, 12.59900387, 14.269074  , 15.93914414,
       17.60921428, 19.27928442, 20.94935455, 22.61942469, 24.28949483,
       25.95956497, 27.6296351 , 29.29970524, 30.96977538, 32.63984552,
       34.30991565, 35.97998579, 37.65005593, 39.32012607, 40.9901962 ,
       42.66026634, 44.33033648, 46.00040662, 47.67047675, 49.34054689,
       51.01061703, 52.68068716, 54.3507573 , 56.02082744, 57.69089758])

In [38]:
y1

array([  5.99804632,   9.24862371,  13.78295405,  17.40423013,
        21.12157435,  25.63825657,  29.37183297,  33.17628385,
        37.27549262,  41.87528987,  45.13753027,  49.84285737,
        53.57274705,  57.47735197,  61.27094404,  65.60216821,
        69.43543114,  73.64645723,  77.1882069 ,  81.19481045,
        85.15673191,  89.04078678,  93.37612418,  97.33140168,
       101.10564161, 105.78780209, 109.27442723, 113.34916788,
       117.42274459, 121.46335655, 125.06531315, 129.73425781,
       133.12136526, 137.76320757, 141.82670011])

In [39]:
error = (sum((y1-yp1)**2))/70

In [40]:
error

1250.0958565296723

In [18]:
while(error>1):
    
    dj0 = (sum(y1 - yp1))/35          #dj0 = dj/dw0 and dj1 = dj/dw1
    dj1 = (sum((y1 - yp1) * x1))/35
    w0 = w0 + (alpha*dj0)
    w1 = w1 + (alpha*dj1)
    yp1=w0+w1*x1
    error = (sum((y1-yp1)**2))/70
    print(error)
    

169315.38253783027
1441054.9432122398
12265085.773842352
104390585.33004421
888489207.373366
7562109996.121775
64362636332.07119
547803319308.0594
4662464028152.982
39683167384541.21
337751404442276.7
2874670010518758.0
2.446689358115839e+16
2.0824264326732326e+17
1.7723949438500216e+18
1.5085209194893335e+19
1.2839324397945861e+20
1.0927806758655507e+21
9.300875720035737e+21
7.916162050635812e+22
6.737604446959088e+23
5.734510409629223e+24
4.880756936241318e+25
4.154110215000551e+26
3.535646602320106e+27
3.0092598052302883e+28
2.561241434433037e+29
2.1799240045857692e+30
1.8553770846758078e+31
1.5791486855039384e+32
1.3440451493797276e+33
1.14394380982225e+34
9.736335424703272e+34
8.286790547611032e+35
7.053053801509558e+36
6.002995688279994e+37
5.10927014703836e+38
4.3486023963640404e+39
3.701182802523105e+40
3.150150988544411e+41
2.6811567490972068e+42
2.281986336328323e+43
1.9422443842355003e+44
1.6530831881158087e+45
1.4069722888691756e+46
1.1975023615732799e+47
1.019218301112483e

C:\Users\Parul\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in double_scalars
  
C:\Users\Parul\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in square
  
C:\Users\Parul\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in double_scalars
  after removing the cwd from sys.path.
C:\Users\Parul\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in multiply
  import sys


In [19]:
w0

2.8255024610253447

In [20]:
w1

4.116156971383036

In [21]:
yp2=w0+w1*x2

In [22]:
yp2

array([146.89099646, 151.00715343, 155.1233104 , 159.23946737,
       163.35562434, 167.47178132, 171.58793829, 175.70409526,
       179.82025223, 183.9364092 , 188.05256617, 192.16872314,
       196.28488012, 200.40103709, 204.51719406])

In [23]:
y2

array([145.86389517, 149.54240175, 153.17283159, 157.46113565,
       161.35791887, 165.32854664, 169.58893134, 173.73442268,
       177.96356669, 181.74390079, 185.19591412, 189.1465459 ,
       193.61461653, 197.87371394, 201.78557591])

In [24]:
import pandas as pd
table=pd.DataFrame(y2)
table["prediction value"]=yp2

In [25]:
table

0  prediction value
0   145.863895        146.890996
1   149.542402        151.007153
2   153.172832        155.123310
3   157.461136        159.239467
4   161.357919        163.355624
5   165.328547        167.471781
6   169.588931        171.587938
7   173.734423        175.704095
8   177.963567        179.820252
9   181.743901        183.936409
10  185.195914        188.052566
11  189.146546        192.168723
12  193.614617        196.284880
13  197.873714        200.401037
14  201.785576        204.517194