In [1]:
import numpy as np
y = np.mat('1,2,3;4,5,6;7,8,9')
y

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
k = 0
for i in range(0,3):
    k = k+y[i,i]
print(k)

15


In [21]:
k =0
p=0
for i in range(0,2):
    for j in range(0,3):
        k = k+ y[j,p]
    p = p+2
print(k)

30


In [22]:
y = np.array([1,2,3,4,5,6,7,8,9])
print(y)

[1 2 3 4 5 6 7 8 9]


In [24]:
z= np.mat(y.reshape(3,3))
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
x = np.array([1,2,3])
y=np.array([2,4,5])
print(x)
print(y)

[1 2 3]
[2 4 5]


In [52]:
p = x.dot(y)
p

25

In [58]:
x1 = x**2
y1 = y**2
x1
y1

array([ 4, 16, 25], dtype=int32)

In [54]:
x2 = x1.sum()
x2
y2 = y1.sum()
y2

45

In [55]:
x3 = np.sqrt(x2)
x3
y3 = np.sqrt(y2)
y3

6.708203932499369

In [56]:
k =x3*y3
k

25.09980079602227

In [57]:
cos = p/k
print(cos)

0.9960238411119946


In [8]:
import numpy as np
a =([1,2,3],[4,5,6],[7,8,9])
b = ([2,1,3],[4,7,8],[4,5,8])
r = np.dot(a,b)
print(r)

[[ 22  30  43]
 [ 52  69 100]
 [ 82 108 157]]


In [9]:
print(np.transpose(a))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [1]:
import numpy as np
x = np.array([3,4,5,6])
y = np.mean(x)
print(y)

4.5


In [2]:
x.mean()

4.5

In [3]:
x.min()


3

In [4]:
x.sum()

18

In [10]:
import numpy as np
x = np.mat('4,2,1;2,5,3;1,3,4')
print(x)

[[4 2 1]
 [2 5 3]
 [1 3 4]]


In [11]:
np.linalg.det(x)

34.99999999999999

In [12]:
np.linalg.matrix_rank(x)

3

In [13]:
np.linalg.eigvals(x)

array([8.58061563, 3.10622893, 1.31315543])

In [20]:
x = np.array([10,5,8,7,9,4,2,3,6,1])
y = np.array([1,2,3,4,5,6,7,8,9,10])
x.mean()

5.5

In [21]:
x.var()

8.25

In [22]:
np.cov(x,y)


array([[ 9.16666667, -6.61111111],
       [-6.61111111,  9.16666667]])

In [23]:
np.corrcoef(x,y)

array([[ 1.        , -0.72121212],
       [-0.72121212,  1.        ]])

In [24]:
import numpy as np
x = np.mat('2,4,5;5,6,7;1,8,7')
np.linalg.det(x)

30.000000000000004

In [26]:
np.linalg.matrix_rank(x)

3

In [27]:
import numpy as np
x = np.mat('2,4,5;4,8,10;1,8,7')
np.linalg.det(x)

0.0

In [28]:
np.linalg.matrix_rank(x)

2

In [29]:
import numpy as np
x = np.mat('2,4,5;4,8,10;2,4,5')
np.linalg.det(x)

0.0

In [30]:
np.linalg.matrix_rank(x)

1