In [2]:
import numpy as np
z =np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
x =np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
q =np.array([1,2,0,0,4,0])
q

array([1, 2, 0, 0, 4, 0])

In [13]:
x = np.where(q!=0)
x

(array([0, 1, 4], dtype=int64),)

In [14]:
q.take(x)

array([[1, 2, 4]])

In [19]:
import numpy as np
q =np.array([1,2,0,0,4,0])
for i in range(0,len(q)):
    if(q[i]!=0):
        print(q[i], end = " ")
        
for i in q:
    if(i==0):
        pass
    else:
        print(i,end = " ")

1 2 4 1 2 4 

In [15]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.random((3,3,3))

array([[[0.0975906 , 0.90641972, 0.20093372],
        [0.10743722, 0.36857756, 0.7988048 ],
        [0.97419175, 0.11961877, 0.69160131]],

       [[0.46121184, 0.74380505, 0.02626326],
        [0.05238201, 0.93409631, 0.14984668],
        [0.7484542 , 0.58639563, 0.97348878]],

       [[0.99983752, 0.95042961, 0.40748147],
        [0.48588084, 0.35543189, 0.36999254],
        [0.8129837 , 0.61898985, 0.73599254]]])

In [18]:
z = np.random.random((10,10))
z

array([[0.48040821, 0.95664092, 0.89438093, 0.88871891, 0.15000818,
        0.68540608, 0.07833399, 0.11524254, 0.95830543, 0.7208591 ],
       [0.64169233, 0.90200689, 0.78092434, 0.42956493, 0.81562413,
        0.93666822, 0.92496119, 0.92194127, 0.59027488, 0.35012698],
       [0.36640517, 0.23119198, 0.51889406, 0.9209667 , 0.58851665,
        0.71361418, 0.89636395, 0.97026326, 0.45675921, 0.46659546],
       [0.11592662, 0.67526876, 0.47962021, 0.86708746, 0.97917323,
        0.43581332, 0.16759505, 0.98412592, 0.58637672, 0.83251871],
       [0.58067236, 0.88212484, 0.45946802, 0.81323752, 0.51884693,
        0.61802935, 0.24088079, 0.99165283, 0.16475443, 0.80471274],
       [0.16846944, 0.31975367, 0.63504467, 0.50904195, 0.59809034,
        0.60944091, 0.94852706, 0.97745308, 0.80653317, 0.21425383],
       [0.16776581, 0.86658932, 0.98435465, 0.68614267, 0.61641457,
        0.67295475, 0.22825821, 0.7823609 , 0.93396862, 0.23531585],
       [0.65093008, 0.81638768, 0.1894576

In [19]:
z.min()

0.007028092248909434

In [20]:
z.max()

0.9916528310893487

In [21]:
z = np.random.random(30)
z

array([0.3361224 , 0.78897597, 0.88456095, 0.96505597, 0.37763761,
       0.29707295, 0.99988986, 0.74685675, 0.50962362, 0.86624419,
       0.31272639, 0.23756488, 0.88954618, 0.85111971, 0.26752481,
       0.99107276, 0.7836253 , 0.29365562, 0.98596561, 0.36115019,
       0.91626846, 0.93252803, 0.12210001, 0.30092218, 0.74032217,
       0.09632709, 0.38560299, 0.56424218, 0.22769434, 0.7964811 ])

In [22]:
z.mean()

0.5942826759197632

In [46]:
z = np.ones((10,10))
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
z[1:9:1,1:9:1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
import numpy as np
x = np.array([[1,2,3,4],[1,2,4,5],[7,8,9,5],[5,7,1,2]])
x


array([[1, 2, 3, 4],
       [1, 2, 4, 5],
       [7, 8, 9, 5],
       [5, 7, 1, 2]])

In [26]:
x[:2,:2]

array([[1, 2],
       [1, 2]])

In [27]:
x[1:,2:]

array([[4, 5],
       [9, 5],
       [1, 2]])

In [28]:
x[:3,1:]

array([[2, 3, 4],
       [2, 4, 5],
       [8, 9, 5]])

In [29]:
x[:,1]

array([2, 2, 8, 7])

In [30]:
x[:,3:]

array([[4],
       [5],
       [5],
       [2]])

In [35]:
x[:3,1:3]

array([[2, 3],
       [2, 4],
       [8, 9]])

In [48]:
x


array([[1, 2, 3, 4],
       [1, 2, 4, 5],
       [7, 8, 9, 5],
       [5, 7, 1, 2]])

In [49]:
x[::3,::2]

array([[1, 3],
       [5, 1]])

In [50]:
x[::2,::3]

array([[1, 4],
       [7, 5]])

In [ ]:
y = np.array([[23,24,25,26,27],[33,34,35,36,37],[43,44,45,46,47],[53,54,55,56,57],[63,64]])