In [3]:
import numpy as np
arr = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,4],[1,5,7,9]])
print("intial array:")
print(arr)

intial array:
[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 4]
 [1 5 7 9]]


In [8]:
n_array = arr[:2,::3]
print(n_array)

[[1 4]
 [4 7]]


In [10]:
index = arr[[1,1,0,3],[3,2,1,0]]
print("showing index of particular required number as(1,3),(1,2),(0,1),(3,0)")
print(index)

showing index of particular required number as(1,3),(1,2),(0,1),(3,0)
[7 6 2 1]


In [12]:
import numpy as np
a = np.array([[1,2],[2,3]])
b = np.array([[2,4],[7,1]])
print(a+1)

[[2 3]
 [3 4]]


In [14]:
import numpy as np
a = np.array([[1,2],[2,3]])
b = np.array([[2,4],[7,1]])
print(b-1)

[[1 3]
 [6 0]]


In [15]:
print(a+b)

[[3 6]
 [9 4]]


In [31]:
print(a.sum())

10


In [ ]:
0 stands for column
1 stands for row

In [67]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.vstack((a,b)))
c = [9,10]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [68]:
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [69]:
print(np.concatenate((a,b),1))

[[1 2 5 6]
 [3 4 7 8]]


In [70]:
print(np.concatenate((a,b),0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [71]:
print(np.column_stack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [72]:
np.r_[a,b]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [74]:
import numpy as np
a = np.array([[1,3,5,7,6,9],
              [1,2,3,4,5,7]])

In [37]:
print(np.hsplit(a,2))

[array([[1, 3, 5],
       [1, 2, 3]]), array([[7, 6, 9],
       [4, 5, 7]])]


In [38]:
print(np.vsplit(a,2))

[array([[1, 3, 5, 7, 6, 9]]), array([[1, 2, 3, 4, 5, 7]])]


In [43]:
import numpy as np
a = np.array([2,4,6])
b = 2
print(a*b)
c = [2,2,2]
print(a*c)

[ 4  8 12]
[ 4  8 12]


In [ ]:
making indentity matrix..........................

In [80]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
a = np.array([0.0,10.0,20.0,30.0])
b = np.array([0.0,1.0,2.0])
print(a[:,np.newaxis] +b)

[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


In [ ]:
column wise sum

In [57]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.sum(axis = 0))

[5 7 9]


In [ ]:
row wise sum

In [56]:
print(a.sum(axis=1))

[ 6 15]


In [58]:
print(a.ravel())

[1 2 3 4 5 6]


In [64]:
import numpy as np
y = np.array([[6,5,4],[1,2,3],[7,8,9]])
print(np.linalg.matrix_rank(y))

2


In [67]:
print(np.linalg.det(y))

3.0451831532575736e-15


In [ ]:
trace = sum daignol values 

In [70]:
print(np.trace(y))

17


In [71]:
print(np.linalg.inv(y))

[[-1.97032484e+15 -4.26903715e+15  2.29871231e+15]
 [ 3.94064967e+15  8.53807429e+15 -4.59742462e+15]
 [-1.97032484e+15 -4.26903715e+15  2.29871231e+15]]


In [74]:
import numpy as np
y = np.array([[6,5,4],[1,2,3],[7,8,9]])
print(np.linalg.matrix_power(y,3))

[[1011 1089 1167]
 [ 466  507  548]
 [1732 1875 2018]]


In [ ]:
solutions of linear equations
x + 2*y = 18
3x + 4*y = 6

In [76]:
a = np.array([[1,2],[3,4]])
b = np.array([18,6])
print(np.linalg.solve(a,b))

[-30.  24.]


In [84]:
y = np.array([1,2,3,4,5,6,7,8,9])
print(y)

[1 2 3 4 5 6 7 8 9]


In [85]:
z= np.mat(y.reshape(3,3))
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np
list1 = [[1,2,3],[4,5,6],[7,8,9]]
x = np.array(list1, dtype = 'float')
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [3]:
x.astype(int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
x.astype(int).astype(str)

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U11')

In [9]:
y = np.array([0,1,2], dtype = 'bool')
y

array([False,  True,  True])

In [20]:
y = np.array([[0,1,2],[1,2,3]])
print('shape:',y.shape)


shape: (2, 3)


In [21]:
y.dtype

dtype('int32')

In [22]:
y.ndim

2

In [26]:
b = y>1
b

array([[False, False,  True],
       [False,  True,  True]])

In [27]:
y[b]

array([2, 2, 3])

In [32]:
y = np.array([[1,2,3,4],[2,3,4,5],[7,8,9,4]])
y

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [7, 8, 9, 4]])

In [30]:
y[::-1]

array([[7, 8, 9, 4],
       [2, 3, 4, 5],
       [1, 2, 3, 4]])

In [31]:
y[::-1,::-1]

array([[4, 9, 8, 7],
       [5, 4, 3, 2],
       [4, 3, 2, 1]])

In [36]:
y[::-1,::-2]

array([[4, 8],
       [5, 3],
       [4, 2]])

In [37]:
y [::-1,::-3]

array([[4, 7],
       [5, 2],
       [4, 1]])

In [41]:
y [::-1,::2]

array([[7, 9],
       [2, 4],
       [1, 3]])

In [61]:
x = np.array(y,dtype = 'float')
x

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [7., 8., 9., 4.]])

In [62]:
x[1,1] = np.nan
x[1,2] = np.inf
x

array([[ 1.,  2.,  3.,  4.],
       [ 2., nan, inf,  5.],
       [ 7.,  8.,  9.,  4.]])

In [67]:
missing_bool = np.isnan(x) | np.isinf(x)
x[missing_bool] = 2
x


array([[1., 2., 3., 4.],
       [2., 2., 2., 5.],
       [7., 8., 9., 4.]])

In [66]:
np.amin(x,axis = 0)

array([1., 2., 2., 4.])

In [70]:
np.amin(x,axis = 1)

array([1., 2., 4.])

In [71]:
np.amax(x,axis = 1)

array([4., 5., 9.])

In [72]:
np.amax(x,axis = 0)

array([7., 8., 9., 5.])

In [73]:
np.cumsum(x)

array([ 1.,  3.,  6., 10., 12., 14., 16., 21., 28., 36., 45., 49.])

In [ ]:
day2...............

In [4]:
import numpy as np
arr2 = np.array([[1,2,3,4], [4,5,6,7],[7,8,9,5]])
arr2a = arr2[:2,:2]
arr2a

array([[1, 2],
       [4, 5]])

In [5]:
import numpy as np
arr2 = np.array([[1,2,3,4], [4,5,6,7],[7,8,9,5]])
arr2[:1,:1] = 100
arr2

array([[100,   2,   3,   4],
       [  4,   5,   6,   7],
       [  7,   8,   9,   5]])

In [8]:
arr2b = arr2[:2,:2].copy()
arr2b[:1,:1] = 101
arr2

array([[100,   2,   3,   4],
       [  4,   5,   6,   7],
       [  7,   8,   9,   5]])

In [ ]:
difference btw flatten and ravel.......

In [19]:
import numpy as np
arr2 = np.array([[1,2,3,4], [4,5,6,7],[7,8,9,5]])
b = arr2.flatten()
b

array([1, 2, 3, 4, 4, 5, 6, 7, 7, 8, 9, 5])

In [20]:
b[0] = 100
b

array([100,   2,   3,   4,   4,   5,   6,   7,   7,   8,   9,   5])

In [18]:
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 5]])

In [23]:
import numpy as np
a = np.array([[1,2,3,4], [4,5,6,7],[7,8,9,5]])
b1 = a.ravel()
b1

array([1, 2, 3, 4, 4, 5, 6, 7, 7, 8, 9, 5])

In [24]:
b1[0] = 100
b1

array([100,   2,   3,   4,   4,   5,   6,   7,   7,   8,   9,   5])

In [25]:
a

array([[100,   2,   3,   4],
       [  4,   5,   6,   7],
       [  7,   8,   9,   5]])

In [ ]:
create sequence........

In [27]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [31]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [32]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [36]:
np.linspace(start=1, stop =50, num = 5, dtype = int)

array([ 1, 13, 25, 37, 50])

In [40]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
a = [1,2,3]
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [44]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3])

In [ ]:
random..............................................................................

In [51]:
np.random.rand(2,2)

array([[0.69529023, 0.15651648],
       [0.48283918, 0.77208318]])

In [52]:
np.random.random(size = [2,2])

array([[0.52506963, 0.397611  ],
       [0.22069778, 0.00107015]])

In [48]:
np.random.randn(2,2)

array([[0.36404099, 0.27719472],
       [1.67378398, 0.51672825]])

In [49]:
np.random.randint(0,10,(2,2))

array([[0, 3],
       [1, 7]])

In [74]:
np.random.randint(1,6,size = [8,4])

array([[4, 4, 4, 5],
       [2, 2, 2, 4],
       [1, 5, 4, 2],
       [1, 3, 5, 3],
       [4, 2, 3, 2],
       [1, 3, 2, 2],
       [5, 1, 5, 5],
       [2, 3, 3, 1]])

In [50]:
np.random.random()

0.37687954090054787

In [53]:
np.random.choice(['a','b','c','d','e'], size = 10)

array(['c', 'b', 'a', 'a', 'a', 'b', 'c', 'a', 'a', 'e'], dtype='<U1')

In [56]:
np.random.choice(['a','b','c','d','e'], size = 10, p =[0.3,0.1,0.2,0.3,0.1])

array(['b', 'e', 'd', 'c', 'e', 'd', 'd', 'a', 'd', 'd'], dtype='<U1')

In [76]:
z = np.random.randint(1,6,size = [8,4])
np.sort(z,axis = 1)

array([[1, 2, 2, 3],
       [2, 2, 2, 3],
       [1, 3, 3, 4],
       [1, 3, 4, 5],
       [1, 1, 1, 3],
       [1, 3, 4, 5],
       [3, 3, 4, 5],
       [1, 2, 5, 5]])

In [78]:
x = np.array([1,5,7,8,9,4,2,10])
sorted = np.argsort(x)
print(sorted)


[0 6 5 1 2 3 4 7]


In [79]:
x[sorted]

array([ 1,  2,  4,  5,  7,  8,  9, 10])

In [ ]:
get index locations........................................

In [59]:
x = np.array([8,8,4,5,9,1,1,2,3])
print("array:",x)
index = np.where(x>5)
print("location required:", index)

array: [8 8 4 5 9 1 1 2 3]
location required: (array([0, 1, 4], dtype=int64),)


In [60]:
x.take(index)

array([[8, 8, 9]])

In [62]:
np.where(x>5,'T','F')

array(['T', 'T', 'F', 'F', 'T', 'F', 'F', 'F', 'F'], dtype='<U1')

In [ ]:
location of max values..................................

In [64]:
np.argmax(x)

4

In [ ]:
location of min values.................................

In [65]:
np.argmin(x)

5

In [11]:
y.tolist()

[0, 1, 2]

In [12]:
x = np.array([1,'a'], dtype = 'object')
x

array([1, 'a'], dtype=object)

In [13]:
x.tolist()

[1, 'a']