In [1]:
import pandas as pd
df = pd.read_csv("poly1.csv")
df

x    y
0    1    1
1    2    3
2    3    8
3    4   16
4    5   25
5    6   33
6    7   52
7    8   66
8    9   79
9   10  105
10  11  120
11  12  139
12  13  163

In [2]:
import numpy as np
x = df.iloc[:,0]
y = df.iloc[:,1]
x = np.array(x)
y = np.array(y)
import matplotlib.pyplot as plt
plt.plot(x,y)
plt.show


<function matplotlib.pyplot.show(*args, **kw)>

In [3]:
# say poly  is 2
import random
w0 = random.random()
w1 = random.random()
w2 = random.random()


In [4]:
yp = w0 +w1*x + w2*(x**2)
yp

array([ 1.15927375,  2.16702168,  3.30049335,  4.55968876,  5.94460791,
        7.4552508 ,  9.09161743, 10.8537078 , 12.7415219 , 14.75505975,
       16.89432134, 19.15930666, 21.55001573])

In [5]:
error = (sum((y-yp)**2))/24

In [6]:
error

2649.4406785652623

In [7]:
alpha = 0.0002

In [8]:
while(error>10):
    dj0 = (sum(y-yp))/12
    dj1 = (sum((y-yp)* x))/12
    dj2 = (sum((y-yp)* (x**2)))/12
    w0 = w0 + (alpha*dj0)
    w1 = w1 + (alpha*dj1)
    w2 = w2 +(alpha*dj2)
    yp=w0+w1*x + w2*(x**2)
    error = (sum((y-yp)**2))/28
    print(error)

572.175334556668
146.14543692554477
39.30225181882994
12.506715764652979
5.786033025609777


In [9]:
w0


0.28421706150200654

In [10]:
w1

0.8970258431535002

In [11]:
w2

0.9254469029984532

In [12]:
yp=w0+w1*x + w2*(x**2)
yp

array([  2.10668981,   5.78005636,  11.30431672,  18.67947088,
        27.90551885,  38.98246063,  51.91029621,  66.6890256 ,
        83.31864879, 101.79916579, 122.1305766 , 144.31288121,
       168.34607963])

In [13]:
y

array([  1,   3,   8,  16,  25,  33,  52,  66,  79, 105, 120, 139, 163],
      dtype=int64)

In [14]:
import pandas as pd
table = pd.DataFrame(y)
table["pred val"] = yp
table["diff"] = table[0] -  table["pred val"]
table

0    pred val      diff
0     1    2.106690 -1.106690
1     3    5.780056 -2.780056
2     8   11.304317 -3.304317
3    16   18.679471 -2.679471
4    25   27.905519 -2.905519
5    33   38.982461 -5.982461
6    52   51.910296  0.089704
7    66   66.689026 -0.689026
8    79   83.318649 -4.318649
9   105  101.799166  3.200834
10  120  122.130577 -2.130577
11  139  144.312881 -5.312881
12  163  168.346080 -5.346080