In [1]:
import numpy as np
a = np.array([0.0,10.0,20.0,30.0])
b = np.array([0.0,1.0,2.0])
print(a[:,np.newaxis] +b)

[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


In [2]:
import numpy as np
y = np.array([[6,5,4],[1,2,3],[7,8,9]])
print(np.linalg.matrix_power(y,3))

[[1011 1089 1167]
 [ 466  507  548]
 [1732 1875 2018]]


In [3]:
x = np.array([1,5,7,8,9,4,2,10])
sorted = np.argsort(x)
print(sorted)

[0 6 5 1 2 3 4 7]


In [7]:
x[sorted]

array([ 1,  2,  4,  5,  7,  8,  9, 10])